---
title: ''
output: html_document
date: "2023-08-14"
---

### Assignment 1

```{r setup, include=FALSE}
alpha = 61
beta = 41
theta = seq(0, 1, by=0.001)

prior = 1.0
lik = dbeta(theta, alpha, beta)
post = prior * lik 

plot(theta, post, xlab = "Theta", ylab = "Posterior Density", type = "l")
```

### Assignment 2

#### 1d)

```{r}
theta = seq(0, 1, by=0.001)

prior_alpha = 1.0
prior_beta = 0.5

posterior_alpha = 7
posterior_beta = 4.5

prior = dgamma(theta, prior_alpha, prior_beta)

posterior = dgamma(theta, posterior_alpha, posterior_beta)

{
plot(theta, prior, xlab = "Theta", ylab = "Prior Density", type = "l")
plot(theta, posterior, xlab = "Theta", ylab = "Posterior Density", type = "l")
}
```

#### 2a)

```{r}
theta = seq(0, 1, by=0.001)

prior_alpha = 7
prior_beta = 3

prior = dbeta(theta, prior_alpha, prior_beta)

plot(theta, prior, xlab = "Theta", ylab = "Prior Density", type = 'l')

prior_norm = dbeta(theta, prior_alpha, prior_beta)/sum(prior)

plot(theta, prior_norm, xlab = "Theta", ylab = "Prior Probabilities", type = 'l')
```



```{r}
cumsum(prior_norm)[length(prior_norm)]
```

Probabilities sum to 1, as proven.

#### 2b)

```{r}
theta = seq(0, 1, by=0.001)
 
x = 3
n = 5

lik = dbinom(x, prob = theta, size = n)

plot(theta, lik, xlab = "Theta", ylab = "Likelihood Function", type = 'l')
```

