```{r}
model_1 = "model {
  lambda ~ dgamma(0.001, 0.001)
  mu = 1/lambda
  for (i in 1:length(inter_eruption_time)) {
    inter_eruption_time[i] ~ dexp(lambda)
  }
}"

# sort out data
eruption_years <- c(1177, 1262, 1311, 1357, 1416, 1440, 1450, 1500, 1550, 1580, 1612, 1625, 1660, 1721, 1755, 1823, 1860, 1918)

data <- data.frame(inter_eruption_time = numeric())

for (i in 1:(length(eruption_years) - 1)) {
  inter_eruption_time <- eruption_years[i + 1] - eruption_years[i]
  data <- rbind(data, data.frame(inter_eruption_time = inter_eruption_time))
}

data <- rbind(data, data.frame(inter_eruption_time = NA))

variable_names = c("lambda", "mu", "inter_eruption_time")
```

```{r}
# How many proper steps?
steps = 100000

# Thinning?
thin = 10

# Import the rjags library
library("rjags")

# Create a JAGS model object
jm = jags.model(textConnection(model_1), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

```{r}
hist(results$mu, breaks = 50)
```
Estimate the posterior probability that the time between less than 50 years.

```{r}
sum(results$mu < 50) / length(results$mu)
```

Prior Predictive Distribution of New Intereruption Time

```{r}
hist(results$`inter_eruption_time[18]`, breaks = 50)
```

```{r}
sorted = sort(results$`inter_eruption_time[18]`)
post_median = sorted[0.5*length(results$`inter_eruption_time[18]`)]
post_median
```



What would you need to add to the JAGS code to obtain an estimate of the posterior predicted year of the next eruption?

```{r}
model_2 = "model {
  lambda ~ dgamma(0.001, 0.001)
  mu = 1/lambda
  for (i in 1:length(inter_eruption_time)) {
    inter_eruption_time[i] ~ dexp(lambda)
  }
  
  new_year <- 1918 + eruption_years_new
  eruption_years_new ~ dexp(lambda)
}"

variable_names = c("lambda", "mu", "eruption_years_new")
```

```{r}
# Create a JAGS model object
jm = jags.model(textConnection(model_2), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

```{r}
hist(results$eruption_years_new, breaks = 500)
```
```{r}
mean(results$eruption_years_new)
```

