
```{r}
model = "model
{
  # a is in metres
  log_a ~ dnorm(2, 1/2^2)
  a <- exp(log_a)
  
  # b is in metres per kilogram
  log_b ~ dnorm(-2, 1/2^2)
  b <- exp(log_b)
  
  # c is in metres per square kilogram, it's a bit harder
  # to get a handle on so I'm going wider here
  c ~ dt(0, 1, 1)
  # Sigma is in metres
  log_sigma ~ dnorm(2, 1/3^2)
  sigma <- exp(log_sigma)
  
  # Nu (shape parameter of t distribution) is dimensionless
  log_nu ~ dunif(0, 5)
  nu <- exp(log_nu)
  
  for(i in 1:N)
  {
    mu[i] <- a + b*(x[i] - mean(x)) + c*(x[i] - mean(x))^2
    y[i] ~ dt(mu[i], 1/sigma^2, nu)
  }
}
"
```

```{r}
data = list(N = 28, x = c(37.5, 51.5, 61.3, 61.3, 63.6, 66.1,
70, 92.7, 90.5, 90.5, 94.8, 97, 97, 97, 102, 102, 103.6, 100.4,
108.4, 114, 115.3, 114.9, 114.7, 123.6, 125.8, 119.1, 118.9,
141.1), y = c(6.4, 10.2, 12.4, 13, 13.2, 13, 12.7, 13.9, 15.5,
15.8, 15.8, 16.8, 17.1, 17.8, 14.8, 15.5, 16.1, 16.2, 17.9, 15.9,
15.8, 16.7, 17.6, 16.8, 17, 18.2, 19.2, 18.6))

# variables to monitor
variable_names = c("a", "b", "c", "sigma", "nu")

# How many proper steps?
steps = 100000

# Thinning?
thin = 10

# Import the rjags library
library("rjags")

# Create a JAGS model object
jm = jags.model(textConnection(model), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

### 1a) Plot the data and get acquainted with it. Read the model and make sure you understand
it.

```{r}
plot(data$x, data$y)

# plot lines
for (i in 1:1000) {
  line(x = data$x, y = data$a[i] + results$b[i](data$x - mean(data$x)) + results[], col = rgb(0, 0, 1, alpha = 0.05))
}
}
```

