
### Stocastic -> ~
### Deterministic -> =

```{r}
model = "model
{
  # hyperparameters
  mu_l ~ dunif(-5, 5)
  sigma_l ~ dunif(0, 2)
  
  # logit of hyperparameters
  logit_mu_l = log(mu_l/(1-mu_l))
  logit_sigma_l = log(sigma_l/(1-sigma_l))
  
  for(i in 1:N)
  {
    # l[i]  ̃ dnorm(logit_mu_l, 1/logit_sigma_l^2)
    # theta[i] = exp(l[i]) / (1 + exp(l[i]))
    # success[i] ~ dbin(theta[i], attempts[i])
  }
}
"
```

### JAGS Setup

```{r}
# variables to monitor
variable_names = c("mu_l", "signal_l", "theta", "success")



# How many proper steps?
steps = 100000

# Thinning?
thin = 10

# Import the rjags library
library("rjags")

# Create a JAGS model object
jm = jags.model(textConnection(model), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

### Loading data and running program

```{r}
kobe_df = read.csv("../data/kobe_bryant.csv")
data = list(N = nrow(kobe_df),
            success = kobe_df$successes,
            attempts = kobe_df$attempts)
```


