```{r}
model_1 = "model {
  mu ~ dnorm(0, 1/1000^2)
  log_sigma_betas ~ dnorm(0, 1/10^2)
  sigma_betas <- exp(log_sigma_betas)
  
  # priors for different betas corresponding to each locatiom
  # we could also do the same but for sigma in the likelihood function
  for(i in 1:4) {
    beta[i] ~ dnorm(mu, 1/sigma_betas^2)
  }
  
  log_sigma ~ dnorm(0, 1/10^2)
  sigma <- exp(log_sigma)
  
  # likelihood
  for(i in 1:length(Y)) {
    Y[i] ~ dnorm(beta[location[i]], 1/sigma^2)
  }
}"
```

```{r}
data <- data.frame(
  location = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10)),
  Y = c(78, 88, 87, 88, 83, 82, 81, 80, 80, 89,
            78, 78, 83, 81, 78, 81, 81, 82, 76, 76,
            79, 73, 79, 75, 77, 69, 75, 70, 74, 75,
            77, 69, 75, 70, 74, 83, 80, 75, 76, 75)
)
```



```{r}
# variables to monitor
variable_names = c("sigma_betas", "beta", "sigma", "mu")

# How many proper steps?
steps = 100000

# Thinning?
thin = 10

# Import the rjags library
library("rjags")

# Create a JAGS model object
jm = jags.model(textConnection(model_1), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

```{r}
hist(results$mu, breaks = 500)
```
```{r}
plot(results$`beta[1]`, results$`beta[4]`, cex = 0.05)
```
```{r}
hist(log(results$sigma_betas), breaks = 500)
```

```{r}
hist(log(results$sigma), breaks = 50)
```

```{r}
plot(results$sigma, type = 'l')
```

