---
title: ''
output: html_document
date: "2023-08-14"
---

### Assignment 2

#### 1d)

```{r}
theta = seq(0, 1, by=0.001)

prior_alpha = 1.0
prior_beta = 0.5

posterior_alpha = 7
posterior_beta = 4.5

prior = dgamma(theta, prior_alpha, prior_beta)

posterior = dgamma(theta, posterior_alpha, posterior_beta)

{
plot(theta, prior, xlab = "Theta", ylab = "Prior Density", type = "l")
plot(theta, posterior, xlab = "Theta", ylab = "Posterior Density", type = "l")
}
```

#### 2a)

```{r}
theta = seq(0, 1, by=0.001)

prior_alpha = 7
prior_beta = 3

prior = dbeta(theta, prior_alpha, prior_beta)

plot(theta, prior, xlab = "Theta", ylab = "Prior Density", type = 'l')

prior_norm = dbeta(theta, prior_alpha, prior_beta)/sum(prior)

plot(theta, prior_norm, xlab = "Theta", ylab = "Prior Probabilities", type = 'l')
```



```{r}
cumsum(prior_norm)[length(prior_norm)]
```

Probabilities sum to 1, as proven.

#### 2b)

```{r}
theta = seq(0, 1, by=0.001)

# why do we multiply the two likelihood functions though?
practise.lik = dbinom(3, prob = theta, size = 5)
comp.lik = dbinom(1, prob = theta^2, size = 2)
total_lik = practise.lik * comp.lik

{
plot(theta, total_lik/sum(total_lik), ylab = "Likelihood Probability Functions", type='l')
lines(theta, practise.lik/sum(practise.lik), col='red')
lines(theta, comp.lik/sum(comp.lik), col='blue')
}
```

#### 2c)

```{r}
prior_alpha = 7
prior_beta = 3

prior = dbeta(theta, prior_alpha, prior_beta)
post = prior * total_lik

plot(theta, post, xlab = "Theta", ylab = "Posterior Density", type = 'l')

post_norm = post/sum(post) 

plot(theta, post_norm, xlab = "Theta", ylab = "Posterior Probability", type = 'l')
```

```{r}
post_sum = cumsum(post_norm)

cred_min_val = 0.025
cred_max_val = 0.975

cred_min_val_diff = abs(post_sum - cred_min_val)
cred_max_val_diff = abs(post_sum - cred_max_val)

cred_min_idx = which.min(cred_min_val_diff)
cred_max_idx = which.min(cred_max_val_diff)

{
plot(theta, post_norm, xlab = "Theta", ylab = "Posterior Probability", type = 'l')
abline(v = theta[cred_min_idx])
abline(v = theta[cred_max_idx])
}
```

#### 2d)

```{r}
predictive_lik = dbinom(1, prob = theta^2, size = 1)
# choose competition likelihood function
success_next_comp = sum(post_norm * predictive_lik)
success_next_comp
```

