```{r}
coal_model = "model
{
  # priors
  lambda_1 ~ dunif(0, 10)
  lambda_1 ~ dunif(0, 10)
  t_c ~ dunif(1851, 1962)
  
  # Noise standard deviation
  log_sigma ~ dnorm(0, 1/10^2)
  sigma <- exp(log_sigma)
  
  # Data
  for(i in 1:length(y))
  {
    mu[i] <- beta0 + beta1*x[i]
    y[i] ~ dnorm(mu[i], 1/sigma^2)
  }
}
"
```

Loading dataset

```{r}
# A dataset
data = list(x = c(0.044103595329532, -0.922186227194728, 0.0960010565013454, 
-1.12828522333698, 1.36291783960003, -2.23065969145022, -0.93027082294735, 
-2.07175801570109, 1.20069146950599, 3.3937627148158), N = 10)
```


Running JAGS

```{r}
# Variables to monitor
variable_names = c("mu", "sigma", "a")

# How many proper steps?
steps = 100000

# Thinning?
thin = 10

# Import the rjags library
library("rjags")

# Create a JAGS model object
jm = jags.model(textConnection(model), data)

# Do some MCMC
results = coda.samples(jm, variable_names, steps, thin=thin)

# Extract chains as data frame
results = as.data.frame(results[[1]])
```

